### ISSUE TITLE
collective.sentry still logs ignored Exceptions

### ISSUE THREAD

**Issue by fredvd** [collective/collective.sentry#11] opened 2020-08-21 10:00 UTC
Note for self as well, still have to dig/debug further.  After upgrading to collective.sentry 0.2.3 I still get NotFound and Unauhorized tracebacks sent to sentry from Plone Plone 5.2.1/5.2.2 project, in spite of https://github.com/collective/collective.sentry/pull/8/commits/85c85a62b90f5e341750132eff1e7dd5c5268cf8

Needs more investigation

<img width="528" alt="unfiltered exceptions" src="https://user-images.githubusercontent.com/394784/90878497-e471e580-e3a5-11ea-9ded-62e5aa087c10.png">

**Comment by mauritsvanrees** [comment] 2020-09-07 13:43
From what I see, the `ignored_exceptions` in the Plone `error_log` are ignored correctly. But this only works when Plone is in the path.
For errors on the Zope level, we need to check the error_log in the Zope root. Done in PR #12.

**Comment by zopyx** [comment] 2020-09-07 13:47
Merged and released

https://pypi.org/project/collective.sentry/0.2.4

**Closed by zopyx** 2020-09-07 13:47 UTC

**Comment by thomasmassmann** [comment] 2022-07-26 09:02
@mauritsvanrees , I think the problem is a different one: Errors raised during publication process, which do not lead to a publication error, are still captured by sentry.

Example: an `Unauthorized` error is thrown in the navigation portlet when a parent folder is not accessible. The site is still rendered, but the navigation portlet shows an error. We can capture those events in the `before_send` method. I will create a PR for that.
