### ISSUE TITLE
 TypeError: get() got an unexpected keyword argument 'default' - SENTRY_MAX_LENGTH

### ISSUE THREAD

**Issue by Lunga001** [collective/collective.sentry#24] opened 2023-10-18 16:34 UTC
When doing 
`bin/client1 fg` 
I get the error:
```File "zeocluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 361, in get_provider
    __import__(moduleOrReq)
  File ".../buildout-cache/eggs/cp27mu/collective.sentry-0.3.1-py2.7.egg/collective/sentry/__init__.py", line 4, in <module>
    import collective.sentry.error_handler
  File ".../buildout-cache/eggs/cp27mu/collective.sentry-0.3.1-py2.7.egg/collective/sentry/error_handler.py", line 33, in <module>
    sentry_max_length = int(os.environ.get("SENTRY_MAX_LENGTH", default=512))
    zope.configuration.xmlconfig.ZopeXMLConfigurationError: File ".../buildout-cache/eggs/cp27mu/Products.CMFPlone-5.2.13- 
    py2.7.egg/Products/CMFPlone/meta.zcml", line 38.4-42.10
    File ".../zeocluster/parts/client1/etc/site.zcml", line 12.2-12.39
    TypeError: get() got an unexpected keyword argument 'default'
```

**Comment by gforcada** [comment] 2024-06-04 06:52
This was already fixed and released, right?

I'm closing it, re-open if the problem is still there on the last release

**Closed by gforcada** 2024-06-04 06:52 UTC
